### ISSUE TITLE
端口离奇消失问题

### ISSUE THREAD

**Issue by LoaderTime** [xyqyear/maimaiTouchControl#1]
新版程序上传之后，正常打开程序，看见tx和rx灯闪了几下然后...我端口呢？（com3连带着leonardo一起消失了，直接bad）
只修改了config.h的分区代码（就是Group A-E的分区，其它没改）

**Comment by xyqyear** [comment]
你可以先试试什么都不修改然后上传试试运行。如果直接运行可以运行，而修改了配置文件不能运行的话请附上修改之后的config。

**Comment by xyqyear** [comment]
致其他看到这个issue的人：该程序mpr的索引是从0开始的，0x5A-0x5D分别是0-3。newmap是从1开始的，如果从newmap迁移过来的话，第一列的数值要全部减一。
