### ISSUE TITLE
关于区块对应针脚号大于7时导致区块无法触摸的问题

### ISSUE THREAD

**Issue by windofxy** [xyqyear/maimaiTouchControl#3]
经我使用电表考证发现是区块的后4个针脚没有被启用(从触摸点针脚到GND端电路为断路)，后面查询MPR121文档发现config.h中的MPR_PADNUMS被设置为8 9 9 8，导致只有前8(9)个针脚启用，将数值改为12 12 12 12即可修复，已经提交了PR #2

**Comment by xyqyear** [comment]
你好，

感谢提出这个issue！ 

我之前的想法是MPR_PADNUMS这个参数也是用户根据实际情况进行调整的，因为理论上来说如果开启未使用的电极，实际使用电极的抗干扰能力会更弱。这是因为MPR121在对电极充电时，只会对开启的电极进行测试，跳过未开启的电极。如果不开启未使用的电极的话， 一个采样窗口中的样本会更多，被平均的样本数量也会更多，所以抗干扰能力也更强。

除此之外，如果MPR121自动搜索出来的CDT超过一定的阈值（大约小于42微秒，计算参考[datasheet](https://www.nxp.com/docs/en/data-sheet/MPR121.pdf)第15页）的话，延迟会超出预设的4ms。

但是实际上每秒的样本可能已经足够多，8-9个电极相对12个电极的样本数量提升最多也就50%，所以可能实际抗干扰能力提升不会有那么多。而且经过多个人的反馈，暂时没有发现有什么问题。所以我会合并你的PR。

\- X
